### PR TITLE
Add support for php 7.3 and 7.4

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by Gunni** [comment]
An error in a file you didn't change?

    FILE: ...is/build/violet-php/streaming-json-encoder/tests/tests/JsonEncoderTest.php
    --------------------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    --------------------------------------------------------------------------------
     274 | ERROR | [x] Expected 0 spaces after reference operator for argument
         |       |     "$actualTokens"; 1 found

**Comment by Riimu** [comment]
That's caused due to update in the linting tools used on the CI. The versions aren't locked down, so small discrepancies like this can happen. I'll addess this in few days.

**Comment by snapshotpl** [comment]
Something is wrong with travis status notification... Build here https://travis-ci.org/github/violet-php/streaming-json-encoder/builds/741246264

**Comment by snapshotpl** [comment]
Travis passed, Scrutinizer fails by some timeout but I think is ready to merge

**Pull request merged**
